# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ae3652319f870b109035baab2a5ba99b023ddc16c2c1c7f8d01723688f33c45cc64c572279e594c1d643528232e4aef21cda28bc58656e274b3b015770a5f19

test:
  secret_key_base: cab31f6396d2388037f61c38bd8017a52c4e523ffd2d15ee65b4c9b1ab0697e5e8192a3d9388acd57dcdca0bcaccc7765549f55180c298348a2ffc7cb4665b64

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
